server:
  port: 8080
  servlet:
    context-path: /car-service

spring:
  application:
    name: CarService
  datasource:
    url: jdbc:postgresql://localhost:5432/education
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false