server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: CarService
  datasource:
    url: jdbc:postgresql://localhost:5432/education
    username: postgres
    password: admin
  liquibase:
    change-log: classpath:liquibase/changelog.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
